### ISSUE TITLE
Couldn't load ROM.

### ISSUE THREAD

**Issue by G7200** [lawrencewoodman/xAce#6]
When I start xAce I get the following runcommand log:
xace: Jupiter ACE emulator v0.5 (by Edward Patel)
Keys:
    F1     - Delete Line
    F3     - Attach a tape image
    F4     - Inverse Video
    F9     - Graphics
    F11    - Spool from a file
    F12    - Reset
    Esc    - Break
    Ctrl-Q - Quit xAce
Couldn't load ROM.

I compiled xAce and would like to run it from RetroPie.
xace="/opt/retropie/emulators/xace/xace %ROM%"
default="xace"

The ROM ace.rom is in the same directory as the "xace" binary.

Thanks for your help!

**Comment by free-variation** [comment]
I believe you need to run it so that the current working directory contains `ace.rom`, not that the ROM file is in the same directory as the binary.
